// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mci_main.Migrations
{
    [DbContext(typeof(MciContext))]
    partial class MciContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("mci_main.Models.Practitioner", b =>
                {
                    b.Property<int>("MciIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Title")
                        .HasColumnType("INTEGER");

                    b.HasKey("MciIdx");

                    b.ToTable("Practitioner");
                });

            modelBuilder.Entity("mci_main.Models.Specialty", b =>
                {
                    b.Property<int>("MciIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MciIdx");

                    b.ToTable("Specialisation");
                });

            modelBuilder.Entity("PractitionerSpecialty", b =>
                {
                    b.Property<int>("PractitionersMciIdx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialtiesMciIdx")
                        .HasColumnType("INTEGER");

                    b.HasKey("PractitionersMciIdx", "SpecialtiesMciIdx");

                    b.HasIndex("SpecialtiesMciIdx");

                    b.ToTable("PractitionerSpecialty", (string)null);
                });

            modelBuilder.Entity("PractitionerSpecialty", b =>
                {
                    b.HasOne("mci_main.Models.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionersMciIdx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mci_main.Models.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesMciIdx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
